### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small and useless PR adds a link to get your app on F-Droid 👍

### CODE REVIEW

**Comment by thermatk** [comment]
Hi!
We can do better then and add Get it on pics for both?:smile:

**Comment by Poussinou** [comment]
Sure we could 😄 
I know where to find the "Get it on" image for F-Droid, but what picture do you want to use for the Xposed Repo? :)

**Comment by thermatk** [comment]
I've seen some like [that](https://snaptools.io/wp-content/uploads/2015/06/app_badges_xposed-266x86.png), but as I couldn't find any official either, let's leave it like that

**Comment by Poussinou** [comment]
OK :)

**Pull request merged**
