### PR TITLE
Make it possible to exclude certain apps

### PR DESCRIPTION
**Pull request by haffenloher**
...namely F-Droid, which does not want to update microg software packages unless it sees the correct package signature.

Unfortunately, I had to create a service just for resolving UIDs to package names (apparently, one needs some kind of context to do that).

### CODE REVIEW

**Comment by bonanza123** [comment]
Cool, I will try this out on Monday evening and report :-)

**Comment by thermatk** [comment]
How is it going? Can't test right now, so need reports.
And what's the point? I mean, I was always using self-built microg packages, are those on F-Droid already with gms and vending capabilities? Or is it for the future?

**Comment by haffenloher** [comment]
> what's the point?

I was setting up my own F-Droid repo for GmsCore, Blankstore, FakeGapps etc. (see [here](http://o9i.de/2015/10/23/howto-gmscore.html)) and encountered this problem on the way. At first I actually thought I was hitting some strange F-Droid bug before the signature faking finally came to mind ;)

PS: Here's the diff without whitespace changes, to make it a little easier to read:
https://github.com/thermatk/FakeGApps/pull/6/files?w=1

**Comment by bonanza123** [comment]
I built it and I'm having a lot of xposed exceptions (running latest omnirom nightly for nexus5): https://gist.github.com/bonanza123/2adb8fcd77d9dabd3000

**Comment by haffenloher** [comment]
@bonanza123: Thanks for your log! I think I got it now, could you test it once again?

**Comment by bonanza123** [comment]
Here is a new log: https://gist.github.com/bonanza123/18ca76c5df96e60ba0b0 which gives a lot of ```java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference``` errors

**Comment by haffenloher** [comment]
Thanks again! I was finally able to set everything up in an emulator to reproduce your problem. Everything works fine for me now both on Android 4.2 and 5.1.

**Comment by bonanza123** [comment]
I can confirm that's it's working on my device. Thanks! 

@thermatk if you are fine with that, I could merge it and upload a new apk.

**Pull request merged**
